name: Build sketch
on: [push, pull_request]
jobs:
  build:
    name: Test compiling examples for esp32
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout custom library
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/ESPAsyncWebServer
          ref: master
          path: CustomESPAsyncWebServer # must contain string "Custom"

      - name: Checkout custom library
        uses: actions/checkout@v2
        with:
          repository: ayushsharma82/AsyncElegantOTA
          ref: master
          path: CustomAsyncElegantOTA # must contain string "Custom"

      - name: "Compile sketch"
        uses: ArminJo/arduino-test-compile@v3
        with:
          sketch-names: "led_strip.ino"
          arduino-board-fqbn: "esp32:esp32:esp32"
          platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          required-libraries: HomeSpan
          # sketches-exclude: WhistleSwitch 50Hz
          # build-properties: '{ "air_quality": "-DDEBUG -DFREQUENCY_RANGE_LOW", "SimpleFrequencyDetector": "-DINFO" }'
