name: Build sketch
on: [push, pull_request]
jobs:
  build:
    name: Test compiling examples for esp32
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Compile sketch"
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: "esp32:esp32:esp32:PSRAM=disabled,PartitionScheme=default,CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M,UploadSpeed=115200,DebugLevel=none"
          platform-url: https://dl.espressif.com/dl/package_esp32_index.json
          required-libraries: HomeSpan
          # sketches-exclude: WhistleSwitch 50Hz
          # build-properties: '{ "air_quality": "-DDEBUG -DFREQUENCY_RANGE_LOW", "SimpleFrequencyDetector": "-DINFO" }'
